### ISSUE TITLE
What is the recommended way to uncompress assets with the formula's install command?

### ISSUE THREAD

**Issue by leoaugustov** [Justintime50/.github#1]
As the action demands the release asset to be a `tar.gz` file, how is it expected or recommended to uncompress the file with a one-line formula's install command?

I am not familiar with Ruby code and after some googling, I only found multi-line solutions. Also, I have no experience publishing to Homebrew so forgive me if I am missing some crucial detail.

**Comment by Justintime50** [comment]
Is this question intended for my `homebrew-releaser` repo? If so, this issue should be closed and/or moved to that repo instead as this repo doesn't contain the code in question.

**Comment by leoaugustov** [comment]
Sorry for that, I opened the issue in the wrong repo. I am closing this one and opening another in the right repo.
